name: Deploy Web Application
on:
  push:
    paths:
      - 'webapp/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode private key
      run: echo "$EC2_SSH_KEY" | base64 -d > key.pem
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Set permissions
      run: chmod 600 key.pem

    - name: Copy app files to EC2
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no \
          webapp/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/webapp/

    - name: SSH and start app
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo apt update && sudo apt install -y nodejs nginx && \
           sudo systemctl enable nginx && \
           sudo systemctl start nginx && \
           sed -i '/location \/ {/a proxy_pass http://localhost:3000;\nproxy_http_version 1.1;\nproxy_set_header Upgrade \$http_upgrade;\nproxy_set_header Connection upgrade;\nproxy_set_header Host \$host;\nproxy_cache_bypass \$http_upgrade;' /etc/nginx/sites-available/default && \
           sudo systemctl restart nginx && \
           cd /home/ubuntu/webapp && nohup node server.js &"